// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVLE5_jwH291REQFAJzaTN7YmnDYGyOeA',
    appId: '1:806468328626:web:9c54a2f8abd8531a4c7dab',
    messagingSenderId: '806468328626',
    projectId: 'fir-practices1',
    authDomain: 'fir-practices1.firebaseapp.com',
    storageBucket: 'fir-practices1.appspot.com',
    measurementId: 'G-WR627EJ31X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeogQSzU_5Dh6E53dGzw8u5c9xjKTEemQ',
    appId: '1:806468328626:android:9f4dda7b4224193a4c7dab',
    messagingSenderId: '806468328626',
    projectId: 'fir-practices1',
    storageBucket: 'fir-practices1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkBF_t-MNcHeYMg9Qwj8ChVCeO_ClDD0U',
    appId: '1:806468328626:ios:83bec2f536b433424c7dab',
    messagingSenderId: '806468328626',
    projectId: 'fir-practices1',
    storageBucket: 'fir-practices1.appspot.com',
    iosBundleId: 'com.example.firebasePractices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkBF_t-MNcHeYMg9Qwj8ChVCeO_ClDD0U',
    appId: '1:806468328626:ios:0601bcd143868a844c7dab',
    messagingSenderId: '806468328626',
    projectId: 'fir-practices1',
    storageBucket: 'fir-practices1.appspot.com',
    iosBundleId: 'com.example.firebasePractices.RunnerTests',
  );
}
